#:schema ./carton-schema.json

[package]
name = "carton"
version = "0.1.0"
edition = 17
authors = ["aufam"]
description = "C++ package manager and build system"
readme = "README.md"
repository = "https://github.com/aufam/carton"
homepage = "<todo>"
documentation = "<todo>"
license = "MIT"

[dependencies]
cpx = { version = "0.1.0", features = ["cli", "fmt", "json", "toml"] }
spdlog = "1.17.0"
xxhash = "0.8.3"
reproc = "14.2.7"
