#:schema ./carton-schema.json

[package]
name = "carton"
version = "0.1.0"
edition = 17
authors = ["aufam"]
description = "C++ package manager and build system"
readme = "README.md"
repository = "https://github.com/aufam/carton"
homepage = "<todo>"
documentation = "<todo>"
license = "MIT"

[dependencies]
cpx = { version = "0.1.0", features = ["fmt", "json", "toml", "magic_enum", "cli"] }
spdlog = { version = "1.17.0", default-features = false }
xxhash = "0.8.3"
reproc = "14.2.7"
preprocessor = "1.88.0"
semver = "0.3.1"
